services:
  - type: web
    name: codequest-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: "pip install -r src/requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codequest-db
          property: connectionString
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false

databases:
  - name: codequest-db
    plan: free
